### ISSUE TITLE
Enemy Behavior (see comment)

### ISSUE THREAD

**Issue by DevonS3** [GreenFour/pencil-knight#47]
Crow: Should fly vertically and horizontally. (player needs to time their shot to hit it. Not just fire and forget at a static y position).
      Other Ideas: Maybe have him steal items? (so if the Hero doesn't kill Crow fast enough, Crow will be able to get to a health/energy pickup).

Soldier-Shield: If he is hit from the front when not slashing or shooting, then he takes no damage.
      Other Ideas: He shouldn't turn his back on Hero willy nilly. Hero should have to do something other than wait to hit him in the back. I like the idea of shooting to make him go into a "block" state, so when you jump over him you can get his back. Shouldn't be too easy though. Small enough window to give player a sense of executing a well-timed attack.
      Maybe let energized projectile do partial damage through shield?

Dino: He will fire homing rockets. Should have a large health pool. He should always be spawned behind enemies. (dodging the rockets while dealing with other enemies is what makes him a meaningful enemy).

Leo: I think we should have him be a surprise attack kind of enemy. He needs to be fast enough or spawn close enough to Hero to be a threat, otherwise he's a just a bullet sponge with no significant threat to the player.

More for the others later.

**Comment by Saerith** [comment]
Can we make these separate issues?
