### ISSUE TITLE
Soldier-Shield Behavior (Heretofore known as SS, which is expressly *not* in reference to Nazis in any way shape or form).

### ISSUE THREAD

**Issue by DevonS3** [GreenFour/pencil-knight#52]
EDIT: To keep this somewhat clean, If you want to comment on a specific thread (projectiles, for example), click on the ellipse, press edit, then write your stuff above everything else with a _____ line above where the old stuff was. Like I just did here!
________________________________
Discuss tweaks, design ideas, and anything related to SS here.

**Comment by DevonS3** [comment]
PROJECTILE THREAD

**Comment by DevonS3** [comment]
PROJECTILES: 
Currently he has a single projectile. I programmed it with the idea that it is a moving shield of sorts (it destroys normal Hero shots in one hit, and super Hero shots in 2). I like the idea of his attacks having a defensive nature. The tough bullets make it so that Hero needs to do more than blast through them.

POSSIBLE CHANGES TO RED BULLET:
Longer cooldown time between shots. 
Slower moving, maybe with slightly bigger hitbox. 
[Taken together, these would mean we want to either give him some smaller, weaker, and faster bullets in addition to red, or that we want to make sure he is accompanied by the original soldier to shoot those kinds of bullets for him].

IDEA FROM ALYSSA: Let slashing reflect red bullet, and let red bullet destroy the next red bullet it interacts with.
    ---DS3: I really, *really* like this idea (as long as the reflect costs energy). I think we should give this functionality to Cleave on energize. Cleave already has a defensive hurtbox, and it doesn't have an energized function yet, so I think this would make the most sense.

**Comment by Saerith** [comment]
I like the idea that the Hero has to do more than just hold "shoot" to kill these. Currently they are only vulnerable to damage while shooting, swinging a sword, or have their back turned. Having defensive bullets PLUS a shield is pretty rough, at least if there are other enemies to deal with, too, but I think it's a good concept.
