### ISSUE TITLE
Enemies try to interact with the hero regardless of how far away they are

### ISSUE THREAD

**Issue by Saerith** [GreenFour/pencil-knight#54]

**Comment by Saerith** [comment]
I suggest a simple sight range check block in ai behaviors.

**Comment by adam-kuhn** [comment]
I'd like to try my hand at this

**Comment by Saerith** [comment]
I actually just pushed a simple version to feat/behavior

**Comment by Saerith** [comment]
@adam-kuhn this repo is actually for a term project! I don't think our professor would like contributions from somebody not on our predefined team, but it's really cool that you'd like to contribute. Feel free to fork!
